name: Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages & build prod wp theme
        run: |
          ls
          rm README.md
          ls
          cd wp-content/themes/budlandscapes/
          ls
          npm install
          npm run prod
          ls
          echo '>>>> remove stuff'
          rm -rf assets
          rm local-example.json
          rm -rf node_modules
          rm package-lock.json
          rm package.json
          rm readme.md
          rm tailwind*.js
          rm webpack.*.js 
          echo '>>>> AFTER REMOVE stuff'                                            
          ls
          echo '>>>> BACK UP TO ROOT' 
          cd ../../../
          rm .gitignore
          rm -rf .git
          rm -rf .github
          echo '>>>> PATH AND FILES LEFT' 
          pwd
          ls

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-folder
          path: |
            *

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Download build folder
        uses: actions/download-artifact@v2
        with:
          name: build-folder

      - name: Add to git
        run: |
          ls
          git init
          git config user.email "whybrow.elton@gmail.com"
          git config user.name "Elton Whybrow"
          git add -A && git commit -m "Add compiled build to git"
          ls
          git ftp push -v --force --user ${{ secrets.FTP_USER_STAGING }} --passwd ${{ secrets.FTP_PWD_STAGING }} ftp://ftps1.uk.cloudlogin.co
